// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuzw-I4elV1x8J21aA0H0olMvzqxECcMk',
    appId: '1:515151266891:web:dc695ab3124e0655ea39ce',
    messagingSenderId: '515151266891',
    projectId: 'my-portfolio-5f576',
    authDomain: 'my-portfolio-5f576.firebaseapp.com',
    databaseURL: 'https://my-portfolio-5f576-default-rtdb.firebaseio.com',
    storageBucket: 'my-portfolio-5f576.appspot.com',
    measurementId: 'G-GZYG4ZX1C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7nw0dCooV8IvUbINhU2Eyh2Qk82lq3Go',
    appId: '1:515151266891:android:98793c0fa08438baea39ce',
    messagingSenderId: '515151266891',
    projectId: 'my-portfolio-5f576',
    databaseURL: 'https://my-portfolio-5f576-default-rtdb.firebaseio.com',
    storageBucket: 'my-portfolio-5f576.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZH3xKk9jtfwqJhUU6VNNlFJzmV4yGrn4',
    appId: '1:515151266891:ios:00ec3a337ef89727ea39ce',
    messagingSenderId: '515151266891',
    projectId: 'my-portfolio-5f576',
    databaseURL: 'https://my-portfolio-5f576-default-rtdb.firebaseio.com',
    storageBucket: 'my-portfolio-5f576.appspot.com',
    iosClientId: '515151266891-2qrattakte6l8t7tkfvmae4lp06jtjjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeezus2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZH3xKk9jtfwqJhUU6VNNlFJzmV4yGrn4',
    appId: '1:515151266891:ios:00ec3a337ef89727ea39ce',
    messagingSenderId: '515151266891',
    projectId: 'my-portfolio-5f576',
    databaseURL: 'https://my-portfolio-5f576-default-rtdb.firebaseio.com',
    storageBucket: 'my-portfolio-5f576.appspot.com',
    iosClientId: '515151266891-2qrattakte6l8t7tkfvmae4lp06jtjjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeezus2',
  );
}
